### ISSUE TITLE
WaveBank.IsPrepared regression in behaviour from FNA/XNA

### ISSUE THREAD

**Issue by teamtwentythree** [flibitijibibo/FACT#3]
WaveBank.IsPrepared should be set during load without requiring a sound to be played or selected.  I'm unsure as to the specifics of what is complete in order for this to be set.  Tested in FNA and XNA:

- FNA: IsPrepared seems to be set immediately after the creation of the WaveBank.

- XNA: IsPrepared is not set immediately, but will be set after running the below loop.

- FNA-FACT: IsPrepared is not set immediately and does not appear to be set after running the below loop.  Playing a song from the sound bank will function but it will not set IsPrepared either.

`while (!MusicWaveBank.IsPrepared) { Engine.Update(); }`

**Comment by flibitijibibo** [comment]
https://github.com/flibitijibibo/FACT/commit/3252f8772c8f93c93ad8743c85906486125feb1f
